version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: nginx
        ports:
            - 80:80
            - 6001:6001
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
            - postgres
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    postgres:
        image: postgres
        restart: always
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        networks:
            app-network:
                ipv4_address: 10.0.0.8

    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        networks:
            app-network:
                ipv4_address: 10.0.0.9

networks:
    app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"
