version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
            - mysql
        networks:
            - app-network

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: php
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

    mysql:
        image: mysql:5.7
        restart: always
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
            - ./dockerDBData:/var/lib/mysql
        networks:
            app-network:
                ipv4_address: 10.0.0.8

    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        networks:
            app-network:
                ipv4_address: 10.0.0.9

networks:
    app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"
