version: '3'

services:
    nginx:
        build:
            context: .
            dockerfile: ubuntu.dockerfile
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        container_name: gusphp
        depends_on:
            - mysql
        #     - mailhog
        networks:
            gus-php-network:
                ipv4_address: 12.0.0.8

    mysql:
          image: mysql:5.7
          restart: always
          ports:
              - 3306:3306
          environment:
              MYSQL_DATABASE: laravel
              MYSQL_ROOT_PASSWORD: laravel
          networks:
            gus-php-network:
                ipv4_address: 12.0.0.9

networks:
    gus-php-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "12.0.0.0/16"