version: '3'

services:
    # nginx:
    #     build:
    #         context: .
    #         dockerfile: nginx.dockerfile
    #     container_name: nginx
    #     ports:
    #         - 80:80
    #     volumes:
    #         - ./:/var/www/html
    #     depends_on:
    #         - php
    #         - postgres
    #     networks:
    #         - app-network

    php:
        build:
            context: .
            dockerfile: php71.dockerfile
        container_name: php
        ports:
            - 80:80
        volumes:
            - ./:/var/www/html
        depends_on:
            - redis
            - postgres
            - mysql
        networks:
            app-network:
                ipv4_address: 10.0.0.12

    postgres:
        build:
            context: .
            dockerfile: pgsql.dockerfile
        restart: always
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        networks:
            app-network:
                ipv4_address: 10.0.0.8
    
    mysql:
        build:
            context: .
            dockerfile: mysql.dockerfile
        restart: always
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
            - ./dockerDBData:/var/lib/mysql
        networks:
            app-network:
                ipv4_address: 10.0.0.11

    redis:
        image: redis
        container_name: redis
        ports:
            - 6379:6379
        networks:
            app-network:
                ipv4_address: 10.0.0.9

networks:
    app-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "10.0.0.0/16"